version: '3.8'

services:
  back:
    networks:
      - devops
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TalanBD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypassword
    container_name: back
    build: 
      dockerfile: DockerFileBack
      context: "./"
    ports:
      - "5000:8082"

  frontdevops:
    networks:
      - devops
    container_name: frontdevops
    build: 
      dockerfile: DockerFileFront
      context: "./"
    links:
      - "back"
    depends_on:
      - "back"
    ports:
      - "4200:80" 

  db:
    networks:
      -devops
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: TalanBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amouna
    volumes:
      - my-datavolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devops

volumes:
  my-datavolume:

networks:
  devops:
