version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  # Port Jenkins web UI
      - "50000:50000"  # Port pour les connexions d'agent
    volumes:
      - jenkins_home:/var/jenkins_home  

volumes:
  jenkins_home:
