apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: back
          image: miladiemna/backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
    name: back-svc
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 8092 # The port that the service is running on in the cluster
      targetPort: 8092 # The port exposed by the service
      nodePort: 31111